<?php
/**
 * Authored by Chibuzor Ogbu.
 * Email: chibuzorogbu@gmail.com
 * Date: 28/06/2018
 * Time: 3:42 AM
 */


?>


<div class="row">
    <?php foreach ($data as $product): ?>
        <div class="imgbox">
            <a href="#">
                <div class="product" style="background-image: url(<?= $product->img ?>); background-repeat: no-repeat">
                    <label class="product-label"><span><?= $product->name ?></span><br>$<?= $product->price ?></label>
                </div>
            </a>
            <div class="addcart">

                <button onclick="addToCart(<?= htmlspecialchars(json_encode($product)) ?>)" class="btn btn-primary">Add
                    to Cart
                </button>
                <div  class="form-inline rating-bar">

                    <input hidden id="rating-view-<?= $product->id ?>" class="rating" type="text" data-size="xs"
                           data-theme="krajee-fa" data-display-only="true" value="<?= $product->ratingAvg ?>">

                    <a href="#" class="rater-link-overlay" data-toggle="modal" onclick="openRatingWindow(event, <?= $product->id ?>)"></a>

                </div>
                <small class="rating-avg">avg: <span
                            id="rating-view-display-<?= $product->id ?>"><?= $product->ratingAvg ?></span></small>

            </div>
        </div>
    <?php endforeach; ?>
</div>


<!--Rating Modal-->

<div class="modal fade" id="exampleModalCenter" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle"
     aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered modal-sm" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLongTitle">Rate Product</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body center">
                <input id="input-id" type="text" data-size="xs">
            </div>
            <div class="modal-footer center">
                <button type="button" onclick="rateProduct(event)" class="btn btn-primary">Rate it!</button>
            </div>
        </div>
    </div>
</div>
